name: GitHub Invitation
description: I want to join the awesome GitHub organisation
title: "Invite me to the GitHub Community Organization"
labels:
  - "invite me to the organisation"
assignees:
  - Adarsh-jaiss
  - KendallDoesCoding
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Insert your name here
      placeholder: Adarsh Jaiswal
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      description: Insert your Discord username here
      placeholder: "text_adarsh#3904"
    validations:
      required: false
  - type: input
    id: discordname
    attributes:
      label: Twiiter username (if applicable)
      description: Insert your Twitter username here
      placeholder: "collab__"
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you learn about Collab Community? What do you like about this community/Why do you want to join?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Join our [Discord community](https://discord.gg/PGadh3Vyuv)
        Join us on [Twitter](https://twitter.com/collab__)
        Connect with me (the owner of this community, Adarsh Jaiswal) on [Twitter](https://twitter.com/twtadarsh)
